services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./${TEMP_MEDIA_FOLDER}:/app/${TEMP_MEDIA_FOLDER}
    command: bash -c "uvicorn src.server.app:get_app --host 0.0.0.0 --port 8000 --factory"

  postgres:
    image: "postgres:15"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", $POSTGRES_DB]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  taskiq_worker:
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./${TEMP_MEDIA_FOLDER}:/app/${TEMP_MEDIA_FOLDER}
    command: bash -c "taskiq worker src.core.tasks.broker:broker src.media_analyze --worker 1 -fsd"